### ISSUE TITLE
Api not working 

### ISSUE THREAD

**Issue by febs** [joshbirnholz/Magic-Booster-Pack-Generator#4]
Any example found in the README gives this output

{"reason":"Not Found","error":true}

**Comment by Meerkov** [comment]
All the examples in the readme give
{"reason":"Not Found","error":true}

I'm going to assume this is abandoned.

**Comment by Meerkov** [comment]
On closer reading, you have to POST to the url, you can't GET it.

I don't know *why* you would make this only available from post, and not GET, but there you go. I was able to get it to work. (Look at the home page which makes the calls here: https://tts-magic-booster.herokuapp.com/index.html )

**Comment by febs** [comment]
Thanks, that works and is actually pretty cool admittedly.
